Question 1: Array Creation and Manipulation
Q1.1: Create a 4x4 identity matrix using np.eye()

Q1.2: Create an array of 8 zeros using np.zeros()

Q1.3: Create an array of 6 ones using np.ones()

Q1.4: Create an array with values from 0 to 15 using np.arange()

Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

Question 2: Array Attributes and Information
Q2.1: What is the shape of the banking_data array?

Q2.2: What is the data type of the banking_data array?

Q2.3: What is the size (total number of elements) of the banking_data array?

Q2.4: What is the number of dimensions of the banking_data array?

Q2.5: What is the memory size of the banking_data array in bytes?

Question 3: Indexing and Slicing
Q3.1: Extract the first row of banking_data

Q3.2: Extract the last row of banking_data

Q3.3: Extract the Account_Balance column (column index 1)

Q3.4: Extract the first 4 rows and first 3 columns

Q3.5: Extract rows 3 to 7 (inclusive)

Question 4: Mathematical Operations
Q4.1: Calculate the sum of all account balances

Q4.2: Calculate the mean account balance

Q4.3: Calculate the standard deviation of account balances

Q4.4: Calculate the variance of account balances

Q4.5: Calculate the median account balance

Question 5: Statistical Functions
Q5.1: Find the minimum and maximum account balances

Q5.2: Find the minimum and maximum credit scores

Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)

Q5.4: Calculate the correlation between account balance and credit score

Q5.5: Calculate the covariance between account balance and credit score

Question 6: Array Reshaping and Manipulation
Q6.1: Reshape the banking_data to 5 rows × 10 columns

Q6.2: Flatten the banking_data to a 1D array

Q6.3: Transpose the banking_data

Q6.4: Split the banking_data into 2 equal parts vertically

Q6.5: Split the banking_data into 2 equal parts horizontally

Question 7: Logical Operations and Filtering
Q7.1: Find customers with account balance greater than $100,000

Q7.2: Find customers with credit score greater than 800

Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750

Q7.4: Count how many customers have account balance between $10,000 and $100,000

Q7.5: Find the index of the customer with the highest credit score

Question 8: Sorting and Searching
Q8.1: Sort the banking_data by account balance (ascending)

Q8.2: Sort the banking_data by credit score (descending)

Q8.3: Find the indices that would sort the array by years active

Q8.4: Find the customer with the second highest account balance

Q8.5: Find the customer with the lowest transaction count

Question 9: Mathematical Functions
Q9.1: Calculate the absolute values of all elements

Q9.2: Calculate the square root of all account balances

Q9.3: Calculate the square of all credit scores

Q9.4: Calculate the exponential of all transaction counts

Q9.5: Calculate the natural logarithm of all account balances

Question 10: Advanced Operations
Q10.1: Calculate the cumulative sum of account balances

Q10.2: Calculate the cumulative product of transaction counts

Q10.3: Calculate the difference between consecutive account balances

Q10.4: Calculate the gradient of account balances

Q10.5: Calculate the histogram of account balances with 5 bins

Question 11: Random Numbers and Simulation
Q11.1: Generate 6 random integers between 1 and 1000

Q11.2: Generate 6 random floats between 0 and 1

Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

Q11.4: Shuffle the banking_data rows randomly

Q11.5: Set random seed to 123 and generate 4 random numbers

Question 12: Linear Algebra Operations
Q12.1: Calculate the dot product of account balance and credit score columns

Q12.2: Calculate the cross product of first two rows

Q12.3: Calculate the norm (magnitude) of the account balance column

Q12.4: Create a 3x3 matrix and calculate its determinant

Q12.5: Calculate the inverse of the 3x3 matrix

Question 13: String Operations
Q13.1: Convert all customer IDs to strings

Q13.2: Check if any customer ID contains '100'

Q13.3: Convert all customer IDs to uppercase (if they were strings)

Q13.4: Count the length of each customer ID string

Q13.5: Replace '100' with 'CUST' in customer IDs

Question 14: Date and Time Operations
Q14.1: Convert years active to months

Q14.2: Calculate the average years active

Q14.3: Find customers who have been active for more than 5 years

Q14.4: Calculate the total time all customers have been active (in years)

Q14.5: Find the customer with the shortest time active

Question 15: Advanced Array Operations
Q15.1: Apply a function to calculate 5% interest on all account balances

Q15.2: Use np.where to categorize customers by balance ranges

Q15.3: Use np.select to categorize customers by credit score ranges

Q15.4: Use np.piecewise to apply different interest rates based on balance

Q15.5: Use np.apply_along_axis to calculate the sum of each row

Question 16: Array Concatenation and Stacking
Q16.1: Concatenate two arrays horizontally using np.hstack()

Q16.2: Concatenate two arrays vertically using np.vstack()

Q16.3: Concatenate arrays along a specific axis using np.concatenate()

Q16.4: Stack arrays depth-wise using np.dstack()

Q16.5: Create a column stack using np.column_stack()

Question 17: Array Splitting Operations
Q17.1: Split an array into 3 equal parts using np.split()

Q17.2: Split an array at specific indices using np.split()

Q17.3: Split an array horizontally using np.hsplit()

Q17.4: Split an array vertically using np.vsplit()

Q17.5: Split an array into equal chunks using np.array_split()

Question 18: Array Repetition and Tiling
Q18.1: Repeat each element of an array 3 times using np.repeat()

Q18.2: Repeat an entire array 2 times using np.tile()

Q18.3: Repeat a 2D array using np.tile()

Q18.4: Create a pattern using np.tile()

Q18.5: Repeat elements with different counts using np.repeat()

Question 19: Array Comparison and Logical Operations
Q19.1: Compare two arrays for equality using np.array_equal()

Q19.2: Check if arrays are close using np.allclose()

Q19.3: Apply logical AND operation between arrays

Q19.4: Apply logical OR operation between arrays

Q19.5: Apply logical NOT operation to an array

Question 20: Array Set Operations
Q20.1: Find unique elements in an array using np.unique()

Q20.2: Find the intersection of two arrays using np.intersect1d()

Q20.3: Find the union of two arrays using np.union1d()

Q20.4: Find elements in first array but not in second using np.setdiff1d()

Q20.5: Find the symmetric difference between two arrays using np.setxor1d()

Learning Objectives
This assignment covers:

Basic NumPy array operations
Statistical analysis of banking data
Array manipulation and reshaping
Logical operations and filtering
Mathematical functions and linear algebra
String operations and data processing
Performance optimization techniques

In [86]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110],
    "Account_Balance": [1200,5400,2300,7800,1500,6200,9100,3000,4500,6700],
    "Credit_Score": [650,720,600,800,580,690,820,610,700,750],
    "Transaction_Count": [12,25,10,40,8,30,50,15,22,35],
    "Years_Active": [2,5,3,10,1,7,12,4,6,8]
}

df = pd.DataFrame(data)

print(df)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [7]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#Create an array of 8 zeros using np.zeros()
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#Create an array of 6 ones using np.ones()
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
#Create an array with values from 0 to 15 using np.arange()
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
#Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [16]:
np.shape(df)

(10, 5)

In [21]:
#What is the data type of the banking_data array?
print(df.dtypes)

Customer_ID          int64
Account_Balance      int64
Credit_Score         int64
Transaction_Count    int64
Years_Active         int64
dtype: object

In [24]:
#What is the size (total number of elements) of the banking_data array?
print(np.size(df))

50

In [27]:
#What is the number of dimensions of the banking_data array?
print(np.ndim(df))

2

In [62]:
#What is the memory size of the banking_data array in bytes?
df = df.to_numpy()
print(df.nbytes)

400

In [63]:
#Extract the first row of banking_data
df[0]

array([ 101, 1200,  650,   12,    2])

In [41]:
# Extract the last row of banking_data
df[-1]

array([ 110, 6700,  750,   35,    8])

In [47]:
df.columns

Index(['Customer_ID', 'Account_Balance', 'Credit_Score', 'Transaction_Count',
       'Years_Active'],
      dtype='object')

In [48]:
df["Account_Balance"]

0    1200
1    5400
2    2300
3    7800
4    1500
5    6200
6    9100
7    3000
8    4500
9    6700
Name: Account_Balance, dtype: int64

In [55]:
df.iloc[:4,0:3]

   Customer_ID  Account_Balance  Credit_Score
0          101             1200           650
1          102             5400           720
2          103             2300           600
3          104             7800           800

In [56]:
#Extract rows 3 to 7 (inclusive)
df.iloc[3:8]

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4

In [57]:
df["Account_Balance"].sum()

np.int64(47700)

In [58]:
#Extract rows 3 to 7 (inclusive)

df["Account_Balance"].mean()

np.float64(4770.0)

In [59]:
#Calculate the standard deviation of account balances
df["Account_Balance"].std()

2725.211510649729

In [60]:
#Calculate the variance of account balances
df["Account_Balance"].var()

7426777.777777778

In [69]:
#Calculate the median account balance

print(np.median(df["Account_Balance"]))

4950.0

In [74]:
#: Find the minimum and maximum account balances
print(df["Account_Balance"].min(),df["Account_Balance"].max())

1200 9100

In [75]:
# Find the minimum and maximum credit scores
print(df["Credit_Score"].min(),df["Credit_Score"].max())

580 820

In [77]:
#5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
print(df["Account_Balance"].quantile(0.25))  # 25th percentile
print(df["Account_Balance"].quantile(0.50))  # 50th percentile (median)
print(df["Account_Balance"].quantile(0.75))  # 75th percentile

2475.0
4950.0
6575.0

In [79]:
# Calculate the correlation between account balance and credit score
print(df["Account_Balance"].corr(df["Credit_Score"]))

0.9324862142065987

In [80]:
print(df["Account_Balance"].cov(df["Credit_Score"]))

210511.1111111111

In [94]:
print(np.reshape(banking_data,(5,10)))

[[ 101 1200  650   12    2  102 5400  720   25    5]
 [ 103 2300  600   10    3  104 7800  800   40   10]
 [ 105 1500  580    8    1  106 6200  690   30    7]
 [ 107 9100  820   50   12  108 3000  610   15    4]
 [ 109 4500  700   22    6  110 6700  750   35    8]]

In [95]:
df

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [98]:
np.ravel(banking_data)

array([ 101, 1200,  650,   12,    2,  102, 5400,  720,   25,    5,  103,
       2300,  600,   10,    3,  104, 7800,  800,   40,   10,  105, 1500,
        580,    8,    1,  106, 6200,  690,   30,    7,  107, 9100,  820,
         50,   12,  108, 3000,  610,   15,    4,  109, 4500,  700,   22,
          6,  110, 6700,  750,   35,    8])

In [100]:
#Transpose the banking_data
np.transpose(df)

                      0     1     2     3     4     5     6     7     8     9
Customer_ID         101   102   103   104   105   106   107   108   109   110
Account_Balance    1200  5400  2300  7800  1500  6200  9100  3000  4500  6700
Credit_Score        650   720   600   800   580   690   820   610   700   750
Transaction_Count    12    25    10    40     8    30    50    15    22    35
Years_Active          2     5     3    10     1     7    12     4     6     8

In [101]:
np.split(df,2)

c:\ProgramData\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
 0          101             1200           650                 12             2
 1          102             5400           720                 25             5
 2          103             2300           600                 10             3
 3          104             7800           800                 40            10
 4          105             1500           580                  8             1,
    Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
 5          106             6200           690                 30             7
 6          107             9100           820                 50            12
 7          108             3000           610                 15             4
 8          109             4500           700                 22             6
 9          110             6700           750                 35             8]

In [104]:
df

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [107]:
np.hsplit(df,5)

c:\ProgramData\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[   Customer_ID
 0          101
 1          102
 2          103
 3          104
 4          105
 5          106
 6          107
 7          108
 8          109
 9          110,
    Account_Balance
 0             1200
 1             5400
 2             2300
 3             7800
 4             1500
 5             6200
 6             9100
 7             3000
 8             4500
 9             6700,
    Credit_Score
 0           650
 1           720
 2           600
 3           800
 4           580
 5           690
 6           820
 7           610
 8           700
 9           750,
    Transaction_Count
 0                 12
 1                 25
 2                 10
 3                 40
 4                  8
 5                 30
 6                 50
 7                 15
 8                 22
 9                 35,
    Years_Active
 0             2
 1             5
 2             3
 3            10
 4             1
 5             7
 6            12
 7             4
 8             6
 9             8]

In [108]:
df['Account_Balance']>100000

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Account_Balance, dtype: bool

In [109]:
df['Credit_Score']>800

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Credit_Score, dtype: bool

In [112]:
df[(df['Transaction_Count'] > 50) & (df['Credit_Score'] < 750)]

Empty DataFrame
Columns: [Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active]
Index: []

In [113]:
print(df[(df['Account_Balance'] >= 10000) & (df['Account_Balance'] <= 100000)]['Customer_ID'].count())

0

In [116]:
print(df['Credit_Score'].idxmax())

6

In [117]:
df.abs()

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [120]:
np.sqrt(df["Account_Balance"])

0    34.641016
1    73.484692
2    47.958315
3    88.317609
4    38.729833
5    78.740079
6    95.393920
7    54.772256
8    67.082039
9    81.853528
Name: Account_Balance, dtype: float64

In [123]:
#Calculate the square of all credit scores
np.square(df["Credit_Score"])

0    422500
1    518400
2    360000
3    640000
4    336400
5    476100
6    672400
7    372100
8    490000
9    562500
Name: Credit_Score, dtype: int64

In [124]:
np.exp(df["Transaction_Count"])

0    1.627548e+05
1    7.200490e+10
2    2.202647e+04
3    2.353853e+17
4    2.980958e+03
5    1.068647e+13
6    5.184706e+21
7    3.269017e+06
8    3.584913e+09
9    1.586013e+15
Name: Transaction_Count, dtype: float64

In [126]:
np.log(df["Account_Balance"])

0    7.090077
1    8.594154
2    7.740664
3    8.961879
4    7.313220
5    8.732305
6    9.116030
7    8.006368
8    8.411833
9    8.809863
Name: Account_Balance, dtype: float64

In [127]:
np.min(df['Transaction_Count'])

8

In [130]:
print(df["Account_Balance"].nlargest(2))

6    9100
3    7800
Name: Account_Balance, dtype: int64

In [131]:
df.sort_values(by="Account_Balance", ascending=True)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
4          105             1500           580                  8             1
2          103             2300           600                 10             3
7          108             3000           610                 15             4
8          109             4500           700                 22             6
1          102             5400           720                 25             5
5          106             6200           690                 30             7
9          110             6700           750                 35             8
3          104             7800           800                 40            10
6          107             9100           820                 50            12

In [132]:
df.sort_values(by="Credit_Score", ascending=False)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
6          107             9100           820                 50            12
3          104             7800           800                 40            10
9          110             6700           750                 35             8
1          102             5400           720                 25             5
8          109             4500           700                 22             6
5          106             6200           690                 30             7
0          101             1200           650                 12             2
7          108             3000           610                 15             4
2          103             2300           600                 10             3
4          105             1500           580                  8             1

In [133]:
# Find the indices that would sort the array by years active
import numpy as np
np.argsort(df["Years_Active"])

0    4
1    0
2    2
3    7
4    1
5    8
6    5
7    9
8    3
9    6
Name: Years_Active, dtype: int64